backend:
  name: git-gateway
  branch: main

media_folder: "src/img/uploads"
public_folder: "/img/uploads"

collections:
  - label: "Site Data"
    name: "data"
    files:
      - label: "Press Quotes"
        name: "press-quotes"
        file: "src/data/press-quotes.json"
        fields:
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - {label: Quote, name: quote, widget: markdown}
              - {label: Source, name: source, widget: string}
      - label: "Gigs"
        name: "gigs"
        file: "src/data/gigs.json"
        fields:
          - label: "Gigs"
            name: "gigs"
            widget: "list"
            fields:
              - {label: Date, name: date, widget: string}
              - {label: Artist, name: artist, widget: string}
              - {label: "Artist URL", name: artistUrl, widget: string}
              - {label: Venue, name: venue, widget: string}
              - {label: "Venue URL", name: venueUrl, widget: string}
              - {label: City, name: city, widget: string}
              - {label: "Tickets URL", name: ticketsURL, widget: string}
              - {label: Extra, name: extra, widget: markdown}
