backend:
  name: git-gateway
  branch: main

media_folder: "src/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - label: "Press Quotes"
        name: "press-quotes"
        file: "data/press-quotes.json"
        fields:
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - {label: Quote, name: quote, widget: markdown}
              - {label: Source, name: source, widget: string}
