backend:
  name: git-gateway
  branch: main

media_folder: "src/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "Data"
    label: "data"
    files:
      - label: "Press Quotes"
        name: "press-quotes"
        file: "data/press-quotes.json"
        fields:
          - {label: Quote, name: quote, widget: string}
          - {label: Source, name: source, widget: string}
